export const AnalyticsEvents = {
  meetSimonHomepageViewed: "meet_simon_homepage_viewed",
  meetSimonIntroButtonClicked: "meet_simon_intro_button_clicked",
  voiceIntroPageViewed: "voice_intro_page_viewed",
  voiceIntroAutoplayNeeded: "voice_intro_autoplay_needed",
  voiceIntroTapToStartClicked: "voice_intro_tap_to_start_clicked",
  voiceIntroPlaybackStarted: "voice_intro_playback_started",
  voiceIntroPlaybackCompleted: "voice_intro_playback_completed",
  dineInRestaurantOrderClicked: "dine_in_restaurant_order_clicked",
  dineInRestaurantCardViewed: "dine_in_restaurant_card_viewed",
  dineInPaymentAuthorized: "dine_in_payment_authorized",
  dineInPaymentSucceeded: "dine_in_payment_succeeded",
  dineInPaymentFailed: "dine_in_payment_failed",
  dineInPaymentCanceled: "dine_in_payment_canceled",
  tipPaymentSucceeded: "tip_payment_succeeded",
  tipPaymentFailed: "tip_payment_failed",
  chatCannedPromptClicked: "chat_canned_prompt_clicked",
  chatVoiceStartClicked: "chat_voice_start_clicked",
  dineInMenuViewed: "dine_in_menu_viewed",
  dineInCheckoutViewed: "dine_in_checkout_viewed",
  dineInPaymentViewed: "dine_in_payment_viewed",
  dineInCardPaymentViewed: "dine_in_card_payment_viewed",
  dineInDetailsViewed: "dine_in_details_viewed",
  tipStaffPageViewed: "tip_staff_page_viewed",
} as const;
